/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;

// Generated 12-nov-2015 11:57:04 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * AreaDescendants generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "AreaDescendants")
public class AreaDescendants implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Areas areasByAreaId;
	private Areas areasByDescendantId;
	private int level;

	public AreaDescendants() {
	}

	public AreaDescendants(Areas areasByAreaId, Areas areasByDescendantId,
			int level) {
		this.areasByAreaId = areasByAreaId;
		this.areasByDescendantId = areasByDescendantId;
		this.level = level;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaId", nullable = false)
	public Areas getAreasByAreaId() {
		return this.areasByAreaId;
	}

	public void setAreasByAreaId(Areas areasByAreaId) {
		this.areasByAreaId = areasByAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "descendantId", nullable = false)
	public Areas getAreasByDescendantId() {
		return this.areasByDescendantId;
	}

	public void setAreasByDescendantId(Areas areasByDescendantId) {
		this.areasByDescendantId = areasByDescendantId;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
