/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;
// Generated 15-mar-2018 10:39:23 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Inspections generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "Inspections")
public class Inspections implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Areas areas;
	private Larvicides larvicides;
	private Schedules schedules;
	private TableElements tableElementsByTypeId;
	private TableElements tableElementsByStateId;
	private Date startDate;
	private Date finishDate;
	private int inspectionSize;
	private BigDecimal coverage;
	private BigDecimal trapLatitude;
	private BigDecimal trapLongitude;
	private Integer trapId;
	private Date trapDate;
	private Set<Plans> planses = new HashSet<Plans>(0);
	private Set<ReportInspections> reportInspectionses = new HashSet<ReportInspections>(0);

	public Inspections() {
	}

	public Inspections(Areas areas, Larvicides larvicides, TableElements tableElementsByTypeId,
			TableElements tableElementsByStateId, int inspectionSize, BigDecimal trapLatitude, BigDecimal trapLongitude) {
		this.areas = areas;
		this.larvicides = larvicides;
		this.tableElementsByTypeId = tableElementsByTypeId;
		this.tableElementsByStateId = tableElementsByStateId;
		this.inspectionSize = inspectionSize;
		this.trapLatitude = trapLatitude;
		this.trapLongitude = trapLongitude;
	}

	public Inspections(Areas areas, Larvicides larvicides, Schedules schedules, TableElements tableElementsByTypeId,
			TableElements tableElementsByStateId, Date startDate, Date finishDate, int inspectionSize,
			BigDecimal coverage, Set<Plans> planses, Set<ReportInspections> reportInspectionses, BigDecimal trapLatitude,
			BigDecimal trapLongitude, Integer trapId) {
		this.areas = areas;
		this.larvicides = larvicides;
		this.schedules = schedules;
		this.tableElementsByTypeId = tableElementsByTypeId;
		this.tableElementsByStateId = tableElementsByStateId;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.inspectionSize = inspectionSize;
		this.coverage = coverage;
		this.planses = planses;
		this.reportInspectionses = reportInspectionses;
		this.trapLatitude = trapLatitude;
		this.trapLongitude = trapLongitude;
		this.trapId = trapId;
		
	}
	
	
	public Inspections(TableElements tableElementsByTypeId,TableElements tableElementsByStateId, int inspectionSize, Date startDate, Date finishDate,BigDecimal coverage,Areas areas, Schedules schedules,Larvicides larvicides,BigDecimal trapLatitude, BigDecimal trapLongitude, Integer trapId, Date trapDate) {
		this.tableElementsByTypeId = tableElementsByTypeId;
		this.tableElementsByStateId = tableElementsByStateId;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.inspectionSize = inspectionSize;
		this.areas = areas;
		this.larvicides = larvicides;
		this.schedules = schedules;
		this.coverage = coverage;
		this.trapLatitude = trapLatitude;
		this.trapLongitude = trapLongitude;
		this.trapId = trapId;
		this.trapDate = trapDate;
		
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaId", nullable = false)
	public Areas getAreas() {
		return this.areas;
	}

	public void setAreas(Areas areas) {
		this.areas = areas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "larvicideId", nullable = false)
	public Larvicides getLarvicides() {
		return this.larvicides;
	}

	public void setLarvicides(Larvicides larvicides) {
		this.larvicides = larvicides;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scheduleId")
	public Schedules getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Schedules schedules) {
		this.schedules = schedules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeId", nullable = false)
	public TableElements getTableElementsByTypeId() {
		return this.tableElementsByTypeId;
	}

	public void setTableElementsByTypeId(TableElements tableElementsByTypeId) {
		this.tableElementsByTypeId = tableElementsByTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateId", nullable = false)
	public TableElements getTableElementsByStateId() {
		return this.tableElementsByStateId;
	}

	public void setTableElementsByStateId(TableElements tableElementsByStateId) {
		this.tableElementsByStateId = tableElementsByStateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finishDate", length = 10)
	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	@Column(name = "inspectionSize", nullable = false)
	public int getInspectionSize() {
		return this.inspectionSize;
	}

	public void setInspectionSize(int inspectionSize) {
		this.inspectionSize = inspectionSize;
	}

	@Column(name = "coverage", precision = 4)
	public BigDecimal getCoverage() {
		return this.coverage;
	}

	public void setCoverage(BigDecimal coverage) {
		this.coverage = coverage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspections")
	public Set<Plans> getPlanses() {
		return this.planses;
	}

	public void setPlanses(Set<Plans> planses) {
		this.planses = planses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspections")
	public Set<ReportInspections> getReportInspectionses() {
		return this.reportInspectionses;
	}

	public void setReportInspectionses(Set<ReportInspections> reportInspectionses) {
		this.reportInspectionses = reportInspectionses;
	}
	
	@Column(name = "trapLatitude", precision = 9, scale = 6)
	public BigDecimal getTrapLatitude() {
		return this.trapLatitude;
	}

	public void setTrapLatitude(BigDecimal trapLatitude) {
		this.trapLatitude = trapLatitude;
	}

	@Column(name = "trapLongitude", precision = 9, scale = 6)
	public BigDecimal getTrapLongitude() {
		return this.trapLongitude;
	}

	public void setTrapLongitude(BigDecimal trapLongitude) {
		this.trapLongitude = trapLongitude;
	}
	
	@Column(name = "trapId", precision = 9)
	public Integer getTrapId() {
		return this.trapId;
	}

	public void setTrapId(Integer trapId) {
		this.trapId = trapId;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "trapDate", length = 10)
	public Date getTrapDate() {
		return this.trapDate;
	}

	public void setTrapDate(Date trapDate) {
		this.trapDate = trapDate;
	}

}
