/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;
// Generated 26-mar-2018 10:36:56 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Larvicides generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "Larvicides")
public class Larvicides implements java.io.Serializable {

	private Integer id;
	private String name;
	private String unity;
	private BigDecimal dose;
	private String doseName;
	private int waterVolume;
	private boolean enabled;

	public Larvicides() {
	}

	public Larvicides(String name, String unity, BigDecimal dose, String doseName, int waterVolume, boolean enabled) {
		this.name = name;
		this.unity = unity;
		this.dose = dose;
		this.doseName = doseName;
		this.waterVolume = waterVolume;
		this.enabled = enabled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "unity", nullable = false, length = 100)
	public String getUnity() {
		return this.unity;
	}

	public void setUnity(String unity) {
		this.unity = unity;
	}

	@Column(name = "dose", nullable = false, precision = 6)
	public BigDecimal getDose() {
		return this.dose;
	}

	public void setDose(BigDecimal dose) {
		this.dose = dose;
	}

	@Column(name = "doseName", nullable = false, length = 200)
	public String getDoseName() {
		return this.doseName;
	}

	public void setDoseName(String doseName) {
		this.doseName = doseName;
	}

	@Column(name = "waterVolume", nullable = false)
	public int getWaterVolume() {
		return this.waterVolume;
	}

	public void setWaterVolume(int waterVolume) {
		this.waterVolume = waterVolume;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
