/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;

// Generated 15-abr-2015 13:02:34 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Plans generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "Plans")
public class Plans implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Inspections inspections;
	private TableElements tableElements;
	private Users users;
	private Date date;
	private Integer planSize;
	private Set<Visits> visitses = new HashSet<Visits>(0);
	private Set<PlansAreas> plansAreases = new HashSet<PlansAreas>(0);
	private byte houseInterval;
	private byte houseIni;
	private String syncFile;

	public Plans() {
	}

	public Plans(Inspections inspections, TableElements tableElements,
			Users users, Date date, Integer planSize, byte houseInterval, byte houseIni, String syncFile) {
		this.inspections = inspections;
		this.tableElements = tableElements;
		this.users = users;
		this.date = date;
		this.planSize = planSize;
		this.houseInterval = houseInterval;
		this.houseIni = houseIni;
		this.syncFile = syncFile;
	}

	public Plans(Inspections inspections, TableElements tableElements,
			Users users, Date date, Integer planSize, Set<Visits> visitses,
			Set<PlansAreas> plansAreases, String syncFile) {
		this.inspections = inspections;
		this.tableElements = tableElements;
		this.users = users;
		this.date = date;
		this.planSize = planSize;
		this.visitses = visitses;
		this.plansAreases = plansAreases;
		this.syncFile = syncFile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inspectionId", nullable = false)
	public Inspections getInspections() {
		return this.inspections;
	}

	public void setInspections(Inspections inspections) {
		this.inspections = inspections;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateId", nullable = false)
	public TableElements getTableElements() {
		return this.tableElements;
	}

	public void setTableElements(TableElements tableElements) {
		this.tableElements = tableElements;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "planSize", nullable = false)
	public Integer getPlanSize() {
		return this.planSize;
	}

	public void setPlanSize(Integer planSize) {
		this.planSize = planSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plans")
	public Set<Visits> getVisitses() {
		return this.visitses;
	}

	public void setVisitses(Set<Visits> visitses) {
		this.visitses = visitses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plans")
	public Set<PlansAreas> getPlansAreases() {
		return this.plansAreases;
	}

	public void setPlansAreases(Set<PlansAreas> plansAreases) {
		this.plansAreases = plansAreases;
	}

	@Column(name = "houseInterval", nullable = false)
	public byte getHouseInterval() {
		return this.houseInterval;
	}

	public void setHouseInterval(byte houseInterval) {
		this.houseInterval = houseInterval;
	}

	@Column(name = "houseIni", nullable = false)
	public byte getHouseIni() {
		return this.houseIni;
	}

	public void setHouseIni(byte houseIni) {
		this.houseIni = houseIni;
	}
	
	@Column(name = "syncFile", nullable = true, length = 200)
	public String getSyncFile() {
		return this.syncFile;
	}

	public void setSyncFile(String syncFile) {
		this.syncFile = syncFile;
	}

}
