/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;

// Generated 15-abr-2015 13:02:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Profiles generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "Profiles")
public class Profiles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String description;
	//private Set<Users> userses = new HashSet<Users>(0);
	//private Set<Permissions> permissionses = new HashSet<Permissions>(0);
	private Set<ProfileAlerts> profileAlertses = new HashSet<ProfileAlerts>(0);


	public Profiles() {
	}

	public Profiles(String name) {
		this.name = name;
	}
	
	
	public Profiles(String name, String description) {
		this.name = name;
		this.description = description;
	}

	/*public Profiles(String name, String description, Set<Users> userses,
			Set<Permissions> permissionses) {
		this.name = name;
		this.description = description;
		this.userses = userses;
		this.permissionses = permissionses;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profiles")
	public Set<ProfileAlerts> getProfileAlertses() {
		return this.profileAlertses;
	}

	public void setProfileAlertses(	Set<ProfileAlerts> profileAlertses) {
		this.profileAlertses = profileAlertses;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "profiles")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profiles")
	public Set<Permissions> getPermissionses() {
		return this.permissionses;
	}

	public void setPermissionses(Set<Permissions> permissionses) {
		this.permissionses = permissionses;
	}*/

}
