/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;
// Generated 09-feb-2018 11:08:42 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Reportinspections generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "ReportInspections")
public class ReportInspections implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Inspections inspections;
	private Reports reports;

	public ReportInspections() {
	}

	public ReportInspections(Inspections inspections, Reports reports) {
		this.inspections = inspections;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inspectionId", nullable = false)
	public Inspections getInspections() {
		return this.inspections;
	}

	public void setInspections(Inspections inspections) {
		this.inspections = inspections;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reportId", nullable = false)
	public Reports getReports() {
		return this.reports;
	}

	public void setReports(Reports reports) {
		this.reports = reports;
	}

}
