/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;

// Generated 15-abr-2015 13:02:34 by Hibernate Tools 4.3.1

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Samples generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "Samples")
public class Samples implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private UUID uuid;
	private Plans plans;
	private TableElements container;
	private Houses houses;
	private String code;
	private String result;

	public Samples() {
	}

	public Samples(UUID uuid, Plans plans,TableElements container, Houses houses, String code) {
		this.uuid = uuid;
		this.plans = plans;
		this.container = container;
		this.houses = houses;
		this.code = code;
	}

	public Samples(UUID uuid, Plans plans,TableElements container, Houses houses, String code, String result) {
		this.uuid = uuid;
		this.plans = plans;
		this.container = container;
		this.houses = houses;
		this.code = code;
		this.result = result;
	}

	@Id
	@Column(name = "uuid", columnDefinition = "BINARY(16)", unique = true, nullable = false)
	public UUID getUuid() {
		return this.uuid;
	}

	public void setUuid(UUID uuid) {
		this.uuid = uuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "planId", nullable = false)
	public Plans getPlans() {
		return this.plans;
	}

	public void setPlans(Plans plans) {
		this.plans = plans;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "containerId", nullable = false)
	public TableElements getContainer() {
		return this.container;
	}

	public void setContainer(TableElements container) {
		this.container = container;
	}	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "houseUuid", nullable = false)
	public Houses getHouses() {
		return this.houses;
	}

	public void setHouses(Houses houses) {
		this.houses = houses;
	}
	
	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "result", length = 200)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
