/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;

// Generated 25-jun-2015 17:37:36 by Hibernate Tools 4.3.1

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Symptoms generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "Symptoms")
public class Symptoms implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UUID uuid;
	private Persons persons;
	private TableElements tableElements;
	private Visits visits;

	public Symptoms() {
	}

	public Symptoms(UUID uuid, Persons persons, TableElements tableElements,
			Visits visits) {
		this.uuid = uuid;
		this.persons = persons;
		this.tableElements = tableElements;
		this.visits = visits;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false)
	public UUID getUuid() {
		return this.uuid;
	}

	public void setUuid(UUID uuid) {
		this.uuid = uuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "personUuid", nullable = false)
	public Persons getPersons() {
		return this.persons;
	}

	public void setPersons(Persons persons) {
		this.persons = persons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "symptomId", nullable = false)
	public TableElements getTableElements() {
		return this.tableElements;
	}

	public void setTableElements(TableElements tableElements) {
		this.tableElements = tableElements;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "visitUuid", nullable = false)
	public Visits getVisits() {
		return this.visits;
	}

	public void setVisits(Visits visits) {
		this.visits = visits;
	}

}
