/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;

// Generated 15-abr-2015 13:02:34 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * TableHeaders generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "TableHeaders")
public class TableHeaders implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private boolean system;
	private Set<TableElements> tableElementses = new HashSet<TableElements>(0);

	public TableHeaders() {
	}

	public TableHeaders(String name, boolean system) {
		this.name = name;
		this.system = system;
	}

	public TableHeaders(String name, boolean system,
			Set<TableElements> tableElementses) {
		this.name = name;
		this.system = system;
		this.tableElementses = tableElementses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "system", nullable = false)
	public boolean isSystem() {
		return this.system;
	}

	public void setSystem(boolean system) {
		this.system = system;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tableHeaders")
	public Set<TableElements> getTableElementses() {
		return this.tableElementses;
	}

	public void setTableElementses(Set<TableElements> tableElementses) {
		this.tableElementses = tableElementses;
	}

}
