/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;
// Generated 26-mar-2018 10:36:56 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrapLocations generated by hbm2java
 */
@Entity
@Table(name = "TrapLocations")
public class TrapLocations implements java.io.Serializable {

	private Integer id;
	private Traps traps;
	private Date date;
	private BigDecimal longitude;
	private BigDecimal latitude;
	private BigDecimal altitude;
	private String address;
	private String location;
	private boolean enabled;
	private Set<TrapData> trapDatas = new HashSet<TrapData>(0);

	public TrapLocations() {
	}

	public TrapLocations(Traps traps, Date date, boolean enabled) {
		this.traps = traps;
		this.date = date;
		this.enabled = enabled;
	}

	public TrapLocations(Traps traps, Date date, BigDecimal longitude, BigDecimal latitude, BigDecimal altitude,
			String address, String location, boolean enabled, Set<TrapData> trapDatas) {
		this.traps = traps;
		this.date = date;
		this.longitude = longitude;
		this.latitude = latitude;
		this.altitude = altitude;
		this.address = address;
		this.location = location;
		this.enabled = enabled;
		this.trapDatas = trapDatas;
	}
	
	public TrapLocations(Traps traps, Date date, BigDecimal longitude, BigDecimal latitude, BigDecimal altitude,
			String address, String location, boolean enabled) {
		this.traps = traps;
		this.date = date;
		this.longitude = longitude;
		this.latitude = latitude;
		this.altitude = altitude;
		this.address = address;
		this.location = location;
		this.enabled = enabled;		
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trapId", nullable = false)
	public Traps getTraps() {
		return this.traps;
	}

	public void setTraps(Traps traps) {
		this.traps = traps;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "longitude", precision = 9, scale = 6)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 9, scale = 6)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "altitude", precision = 9, scale = 6)
	public BigDecimal getAltitude() {
		return this.altitude;
	}

	public void setAltitude(BigDecimal altitude) {
		this.altitude = altitude;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "location", length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trapLocations")
	public Set<TrapData> getTrapDatas() {
		return this.trapDatas;
	}

	public void setTrapDatas(Set<TrapData> trapDatas) {
		this.trapDatas = trapDatas;
	}

}
