/*******************************************************************************
 * Aedes Alert, Support to collect data to combat dengue
 * Copyright (C) 2017 Fundación Anesvad
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *   
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *   
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *******************************************************************************/
package com.gruposca.sapev.api.connectors.dao.model;
// Generated 26-mar-2018 10:36:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrapData generated by hbm2java
 */
@Entity
@Table(name = "TrapData")
public class TrapData implements java.io.Serializable {

	private Integer id;
	private TableElements tableElements;
	private TrapLocations trapLocations;
	private Traps traps;
	private Date date;
	private Integer eggs;

	public TrapData() {
	}

	public TrapData(TrapLocations trapLocations, Traps traps, Date date) {
		this.trapLocations = trapLocations;
		this.traps = traps;
		this.date = date;
	}

	public TrapData(TableElements tableElements, TrapLocations trapLocations, Traps traps, Date date, Integer eggs) {
		this.tableElements = tableElements;
		this.trapLocations = trapLocations;
		this.traps = traps;
		this.date = date;
		this.eggs = eggs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resultId")
	public TableElements getTableElements() {
		return this.tableElements;
	}

	public void setTableElements(TableElements tableElements) {
		this.tableElements = tableElements;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trapLocationId", nullable = false)
	public TrapLocations getTrapLocations() {
		return this.trapLocations;
	}

	public void setTrapLocations(TrapLocations trapLocations) {
		this.trapLocations = trapLocations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trapId", nullable = false)
	public Traps getTraps() {
		return this.traps;
	}

	public void setTraps(Traps traps) {
		this.traps = traps;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "eggs")
	public Integer getEggs() {
		return this.eggs;
	}

	public void setEggs(Integer eggs) {
		this.eggs = eggs;
	}

}
